package com.infosys.ci.fiusb.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-11-20T10:22:10.538+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "FIUsbWebServiceService", 
                  wsdlLocation = "file:/C:/Projects/EOP/BOBSoapService/src/main/resources/fiusbwebservice.wsdl",
                  targetNamespace = "http://webservice.fiusb.ci.infosys.com/") 
public class FIUsbWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.fiusb.ci.infosys.com/", "FIUsbWebServiceService");
    public final static QName FIUsbWebService = new QName("http://webservice.fiusb.ci.infosys.com/", "FIUsbWebService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Projects/EOP/BOBSoapService/src/main/resources/fiusbwebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FIUsbWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Projects/EOP/BOBSoapService/src/main/resources/fiusbwebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FIUsbWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FIUsbWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FIUsbWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FIUsbWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FIUsbWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FIUsbWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FIUsbWebService
     */
    @WebEndpoint(name = "FIUsbWebService")
    public FIUsbWebService getFIUsbWebService() {
        return super.getPort(FIUsbWebService, FIUsbWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FIUsbWebService
     */
    @WebEndpoint(name = "FIUsbWebService")
    public FIUsbWebService getFIUsbWebService(WebServiceFeature... features) {
        return super.getPort(FIUsbWebService, FIUsbWebService.class, features);
    }

}
