package com.infosys.ci.fiusb.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-11-20T10:22:10.528+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://webservice.fiusb.ci.infosys.com/", name = "FIUsbWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface FIUsbWebService {

    @WebMethod
    @RequestWrapper(localName = "executeService", targetNamespace = "http://webservice.fiusb.ci.infosys.com/", className = "com.infosys.ci.fiusb.webservice.ExecuteService")
    @ResponseWrapper(localName = "executeServiceResponse", targetNamespace = "http://webservice.fiusb.ci.infosys.com/", className = "com.infosys.ci.fiusb.webservice.ExecuteServiceResponse")
    @WebResult(name = "executeServiceReturn", targetNamespace = "")
    public java.lang.String executeService(
        @WebParam(name = "arg_0_0", targetNamespace = "")
        java.lang.String arg00
    );
}
